# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 14 2 0
format E 19 2 0
format F 19 2 0
format G 24 2 0
format H 24 2 0
format M 11 2 0
format N 12 2 0
rightstring A0 = "Totais"
rightstring B0 = "valor"
rightstring C0 = "RECEITAS"
rightstring D0 = "valor"
rightstring E0 = "DESPESAS FIXAS"
rightstring F0 = "valor"
rightstring G0 = "COMIDA"
rightstring H0 = "valor"
rightstring I0 = "LIMPEZA"
rightstring J0 = "valor"
rightstring K0 = "HIGIENE"
rightstring L0 = "valor"
rightstring M0 = "TRANSPORTE"
rightstring N0 = "valor"
rightstring O0 = "PAPELARIA"
rightstring P0 = "valor"
rightstring Q0 = "PONTUAIS"
rightstring R0 = "valor"
rightstring A1 = "RECEITAS"
let B1 = @sum(D1:D50)
rightstring C1 = "Salário"
let D1 = 4000
rightstring E1 = "Aluguel"
let F1 = 1800
rightstring G1 = "Alface"
let H1 = 16.97
rightstring M1 = "Uber"
let N1 = 86.78
rightstring O1 = "Caderno"
let P1 = 0
rightstring Q1 = "Entrada Cinema"
let R1 = 27
rightstring A2 = "DESPESAS FIXAS"
let B2 = @sum(F1:F50)
rightstring E2 = "Imposto PJ"
let F2 = 86.05
rightstring G2 = "Tomate"
let H2 = 13
rightstring M2 = "Ônibus"
let N2 = 0
rightstring Q2 = "visita tecnica geladeira"
let R2 = 50
rightstring A3 = "COMIDA"
let B3 = @sum(H1:H50)
rightstring E3 = "Balé"
let F3 = 260
rightstring G3 = "Pão Francês"
let H3 = 20.36
rightstring Q3 = "travas geladeira"
let R3 = 19.98
rightstring A4 = "LIMPEZA"
let B4 = @sum(J1:J50)
rightstring E4 = "Terapia"
let F4 = 150
rightstring G4 = "Coxa-Sobrecoxa (Baratão)"
let H4 = 82.72
rightstring Q4 = "Farmácia (Santo Remédio)"
let R4 = 41.17
rightstring A5 = "HIGIENE"
let B5 = @sum(L1:L50)
rightstring E5 = "Energia"
let F5 = 147.02
rightstring G5 = "Colorau (Baratão)"
let H5 = 0
rightstring Q5 = "Exame Balé"
let R5 = 200
rightstring A6 = "TRANSPORTE"
let B6 = @sum(N1:N50)
rightstring E6 = "Fundo multa aluguel"
let F6 = 0
rightstring G6 = "Filé de Peito"
let H6 = 77.45
rightstring Q6 = "Fita Isolante"
let R6 = 3
rightstring A7 = "PAPELARIA"
let B7 = @sum(P1:P50)
rightstring G7 = "Pão Ciabata"
let H7 = 9.72
rightstring Q7 = "Escapeout"
let R7 = 59
rightstring A8 = "PONTUAIS"
let B8 = @sum(R1:R50)
rightstring G8 = "Ovo Branco 30und"
let H8 = 40.89
rightstring G9 = "Farinha de Mandioca 1kg"
let H9 = 4.39
rightstring G10 = "Arroz Catarinão 1kg"
let H10 = 3.95
rightstring G11 = "Refeição"
let H11 = 18
rightstring A12 = "investimento"
let B12 = B1-@sum(B2:B10)
rightstring G12 = "Garrafão de Água 20L"
let H12 = 20
rightstring G13 = "Prato de comida"
let H13 = 18
rightstring G14 = "Farinha de Mandioca"
let H14 = 8.78
rightstring G15 = "Arroz Branco"
let H15 = 8.28
rightstring G16 = "Colorau"
let H16 = 4.19
goto H12
movetosheet "Sheet1"
